### ISSUE TITLE
Runtime error: [node event 491]

### ISSUE THREAD

**Issue by davissmith1** [comp426-2022-fall/a04#9]
#### What is happening?
code is throwing an unhandled  node error

#### What does the error say is happening?
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1432:16)
    at listenInCluster (node:net:1480:12)
    at Server.listen (node:net:1568:7)
    at Function.listen (/Users/davissmith/Projects/Comp_426/a04-davissmith1/node_modules/express/lib/application.js:635:24)
    at file:///Users/davissmith/Projects/Comp_426/a04-davissmith1/server.js:48:5
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1459:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5000
}
macbook-pro-83:a04-davissmith1 davissmith$

#### What do you think the error means?
honestly not sure. From looking online it sounds like its some kinda of permission issue with the node package but i couldn't figure out anything conclusive

**Comment by jdmar3** [comment]
This is a common problem and an error that you can google: https://gprivate.com/624g6

Here is the answer: https://stackoverflow.com/questions/69833901/nodejs-address-already-in-use-5000
